#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empowered.Dataverse.Webresources.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DeleteMultiple")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class DeleteMultipleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReferenceCollection Targets
		{
			get
			{
				if (this.Parameters.Contains("Targets"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReferenceCollection)(this.Parameters["Targets"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReferenceCollection);
				}
			}
			set
			{
				this.Parameters["Targets"] = value;
			}
		}
		
		public DeleteMultipleRequest()
		{
			this.RequestName = "DeleteMultiple";
			this.Targets = default(Microsoft.Xrm.Sdk.EntityReferenceCollection);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DeleteMultiple")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class DeleteMultipleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public DeleteMultipleResponse()
		{
		}
	}
}
#pragma warning restore CS1591
