#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empowered.Dataverse.Webresources.Model
{
	
	
	/// <summary>
	/// Samesite mode for Session Cookie: 0 is Default, 1 is None, 2 is Lax , 3 is Strict
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum organization_samesitemodeforsessioncookie
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Default = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lax = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Strict = 3,
	}
}
#pragma warning restore CS1591
