#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empowered.Dataverse.Webresources.Model
{
	
	
	/// <summary>
	/// Options for Template Default View
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum templatedefaultview
	{
		
		/// <summary>
		/// Tiles View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TilesView = 1,
		
		/// <summary>
		/// Grid View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GridView = 2,
		
		/// <summary>
		/// List View
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ListView = 3,
	}
}
#pragma warning restore CS1591
